import { Cormorant_Garamond, Crimson_Pro, Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AuthProvider from "@/components/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"]
});

const cormorantGaramond = Crimson_Pro({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${cormorantGaramond.className} antialiased`}>
        <AuthProvider>
        <Navbar />
        {children}
        <Footer />
        </AuthProvider>
        
      </body>
    </html>
  );
}
